"""simulation readiness: append-only events/subscriptions, plan col, sim state

Revision ID: 488801ec6d09
Revises: 8b0ae9e77aec
Create Date: 2026-08-27 17:56:03.569672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '488801ec6d09'
down_revision: Union[str, None] = '8b0ae9e77aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_pending',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_pending_delivery_date'), 'sim_pending', ['delivery_date'], unique=False)
    op.create_table('sim_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('sim_date', sa.Date(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('billing_invoices_subscription_id_fkey'), 'billing_invoices', type_='foreignkey')
    op.add_column('billing_prices', sa.Column('plan', sa.String(length=64), nullable=True))
    op.alter_column('billing_prices', 'plan_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.add_column('billing_subscriptions', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_billing_subscriptions_subscription_id'), 'billing_subscriptions', ['subscription_id'], unique=False)
    op.add_column('product_events', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_product_events_event_id'), 'product_events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_events_event_id'), table_name='product_events')
    op.drop_column('product_events', 'id')
    op.drop_index(op.f('ix_billing_subscriptions_subscription_id'), table_name='billing_subscriptions')
    op.drop_column('billing_subscriptions', 'id')
    op.alter_column('billing_prices', 'plan_code',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('billing_prices', 'plan')
    op.create_foreign_key(op.f('billing_invoices_subscription_id_fkey'), 'billing_invoices', 'billing_subscriptions', ['subscription_id'], ['subscription_id'])
    op.drop_table('sim_state')
    op.drop_index(op.f('ix_sim_pending_delivery_date'), table_name='sim_pending')
    op.drop_table('sim_pending')
    # ### end Alembic commands ###
