"""sim account state

Revision ID: 8457f17dcf66
Revises: 488801ec6d09
Create Date: 2026-08-27 17:57:23.874697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8457f17dcf66'
down_revision: Union[str, None] = '488801ec6d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_account_state',
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('engagement', sa.String(length=16), nullable=False),
    sa.Column('signup_day', sa.Integer(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sim_account_state')
    # ### end Alembic commands ###
