"""initial operational schema

Revision ID: 8b0ae9e77aec
Revises: 
Create Date: 2026-08-27 17:42:53.115120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b0ae9e77aec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('company_size', sa.String(length=32), nullable=True),
    sa.Column('lead_source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('billing_customers',
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('account_ref', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_billing_customers_account_ref'), 'billing_customers', ['account_ref'], unique=False)
    op.create_index(op.f('ix_billing_customers_email'), 'billing_customers', ['email'], unique=False)
    op.create_table('billing_prices',
    sa.Column('price_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('billing_frequency', sa.String(length=16), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_index(op.f('ix_billing_prices_plan_code'), 'billing_prices', ['plan_code'], unique=False)
    op.create_index(op.f('ix_billing_prices_product_id'), 'billing_prices', ['product_id'], unique=False)
    op.create_table('crm_companies',
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('account_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('company_size', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('lead_source', sa.String(length=64), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=32), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_crm_companies_account_ref'), 'crm_companies', ['account_ref'], unique=False)
    op.create_table('product_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('distinct_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_product_events_account_id'), 'product_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_product_events_distinct_id'), 'product_events', ['distinct_id'], unique=False)
    op.create_index(op.f('ix_product_events_event_at'), 'product_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_product_events_event_name'), 'product_events', ['event_name'], unique=False)
    op.create_table('billing_subscriptions',
    sa.Column('subscription_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('price_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['billing_customers.customer_id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['billing_prices.price_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_billing_subscriptions_customer_id'), 'billing_subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_price_id'), 'billing_subscriptions', ['price_id'], unique=False)
    op.create_table('crm_contacts',
    sa.Column('contact_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=32), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.company_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_crm_contacts_company_id'), 'crm_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_email'), 'crm_contacts', ['email'], unique=False)
    op.create_table('crm_deals',
    sa.Column('deal_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('deal_stage', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.company_id'], ),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_index(op.f('ix_crm_deals_company_id'), 'crm_deals', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_workspaces_account_id'), 'workspaces', ['account_id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('invoice_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.String(length=64), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['billing_customers.customer_id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_billing_invoices_customer_id'), 'billing_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_subscription_id'), 'billing_invoices', ['subscription_id'], unique=False)
    op.create_table('memberships',
    sa.Column('membership_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index(op.f('ix_memberships_account_id'), 'memberships', ['account_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_account_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_billing_invoices_subscription_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_customer_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_workspaces_account_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crm_deals_company_id'), table_name='crm_deals')
    op.drop_table('crm_deals')
    op.drop_index(op.f('ix_crm_contacts_email'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_company_id'), table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_index(op.f('ix_billing_subscriptions_price_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_customer_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_index(op.f('ix_product_events_event_name'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_event_at'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_distinct_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_account_id'), table_name='product_events')
    op.drop_table('product_events')
    op.drop_index(op.f('ix_crm_companies_account_ref'), table_name='crm_companies')
    op.drop_table('crm_companies')
    op.drop_index(op.f('ix_billing_prices_product_id'), table_name='billing_prices')
    op.drop_index(op.f('ix_billing_prices_plan_code'), table_name='billing_prices')
    op.drop_table('billing_prices')
    op.drop_index(op.f('ix_billing_customers_email'), table_name='billing_customers')
    op.drop_index(op.f('ix_billing_customers_account_ref'), table_name='billing_customers')
    op.drop_table('billing_customers')
    op.drop_table('accounts')
    # ### end Alembic commands ###
