# Evidence Project Configuration
# Docs: https://docs.evidence.dev/features/project-settings

project:
  name: 'Product Analytics Platform'
  evidence: '0.4.4'

pages: ./pages

layout:
  page_width: full
  cards: true
  table_of_contents: true
